buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }

    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'
apply plugin: 'org.spongepowered.mixin'

version = '1.0.1'
group = 'com.redblaze908.blazetweaks'
archivesBaseName = 'blazetweaks'

sourceCompatibility = targetCompatibility = '1.8'

repositories {
    mavenCentral()
    maven {
        name = "spongepowered"
        url = "https://repo.spongepowered.org/repository/maven-public/"
    }
}

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'

    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            property 'mixin.config', 'blazetweaks.mixins.json'

            args '-tweakClass', 'org.spongepowered.asm.launch.MixinTweaker'
            args '--mixin.config', 'blazetweaks.mixins.json'
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            property 'mixin.config', 'blazetweaks.mixins.json'

            args '-tweakClass', 'org.spongepowered.asm.launch.MixinTweaker'
            args '--mixin.config', 'blazetweaks.mixins.json'
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2859'
    implementation("org.spongepowered:mixin:0.8.3") {
        exclude module: "guava"
        exclude module: "commons-io"
        exclude module: "gson"
    }
}

mixin {
    add sourceSets.main, "blazetweaks.refmap.json"
}

jar {
    manifest {
        attributes(
            'FMLCorePlugin': 'com.redblaze908.blazetweaks.BlazeCoreMod',
            'FMLCorePluginContainsFMLMod': 'true',
            'ForceLoadAsMod': 'true',
            'MixinConfigs': 'blazetweaks.mixins.json'
        )
    }
}