package com.redblaze908.blazetweaks;

import com.redblaze908.blazetweaks.client.DungeonBoundingBoxRenderer;
import com.redblaze908.blazetweaks.client.EnchantmentGuiHandler;
import com.redblaze908.blazetweaks.client.RejoinHandler;
import com.redblaze908.blazetweaks.commands.CommandBackup;
import com.redblaze908.blazetweaks.commands.CommandLightningFinder;
import com.redblaze908.blazetweaks.commands.CommandRNG;
import com.redblaze908.blazetweaks.commands.CommandRNGWeather;
import com.redblaze908.blazetweaks.events.ChunkGeneratorTracker;
import com.redblaze908.blazetweaks.modules.containers.ShulkerTooltipHandler;

import net.minecraftforge.client.ClientCommandHandler;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import java.util.Collections;

@Mod(modid = BlazeTweaks.MODID, name = BlazeTweaks.NAME, version = BlazeTweaks.VERSION)
public class BlazeTweaks {
    public static final String MODID = "blazetweaks";
    public static final String NAME = "BlazeTweaks";
    public static final String VERSION = "1.0.0";

    public static boolean isDungeonOverlayEnabled = false;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        ModMetadata meta = event.getModMetadata();
        meta.autogenerated = false;
        meta.modId = MODID;
        meta.name = NAME;
        meta.version = VERSION;
        meta.description = "A client-side technical utility toolkit for Minecraft 1.12.2.";
        meta.authorList = Collections.singletonList("RedBlaze908");
        meta.credits = "Inspired by Fallen-Breath and Earthcomputer";
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {

        // RNG
        ClientCommandHandler.instance.registerCommand(new CommandRNG());
        ClientCommandHandler.instance.registerCommand(new CommandRNGWeather());
        ClientCommandHandler.instance.registerCommand(new CommandLightningFinder()); // useless

        // Backup System
        ClientCommandHandler.instance.registerCommand(new CommandBackup());

        // PistonOrder
        MinecraftForge.EVENT_BUS.register(new PistonInspectHandler());

        // ShulkerToolTip
        MinecraftForge.EVENT_BUS.register(new ShulkerTooltipHandler());

        // Rejoin
        MinecraftForge.EVENT_BUS.register(new RejoinHandler());

        // Enchating RNG
        MinecraftForge.EVENT_BUS.register(new EnchantmentGuiHandler());

        // Spawner Overlay
        ChunkGeneratorTracker tracker = new ChunkGeneratorTracker();
        MinecraftForge.TERRAIN_GEN_BUS.register(tracker);
        MinecraftForge.EVENT_BUS.register(tracker);
        MinecraftForge.EVENT_BUS.register(new DungeonBoundingBoxRenderer());

        if (FMLCommonHandler.instance().getSide().isClient()) {
            KeyInputHandler.init();
            MinecraftForge.EVENT_BUS.register(new KeyInputHandler());
            MinecraftForge.EVENT_BUS.register(new PistonOverlayRenderer());
        }
    }
}