package com.example.pistonorderoverlay;

import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import java.util.Collections;

@Mod(modid = PistorderMod.MODID, name = PistorderMod.NAME, version = PistorderMod.VERSION)
public class PistorderMod {
    public static final String MODID = "pistonorderoverlay";
    public static final String NAME = "PistonOrderOverlay";
    public static final String VERSION = "1.0.1";

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        ModMetadata meta = event.getModMetadata();
        meta.autogenerated = false;
        meta.modId = MODID;
        meta.name = NAME;
        meta.version = VERSION;
        meta.description = "Client-side mod to display piston push order and block movement.";
        meta.authorList = Collections.singletonList("RedBlaze908");
        meta.credits = "Inspired by Pistorder by Fallen-Breath";
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        MinecraftForge.EVENT_BUS.register(new PistonInspectHandler());

        if (FMLCommonHandler.instance().getSide().isClient()) {
            KeyInputHandler.init();
            MinecraftForge.EVENT_BUS.register(new KeyInputHandler());
            MinecraftForge.EVENT_BUS.register(new PistonOverlayRenderer());
        }
    }
}